import type { Metadata } from "next";
import { Prompt } from "next/font/google"; // 1. นำเข้าฟอนต์จาก Google
import "./globals.css";

// 2. ตั้งค่าฟอนต์
const prompt = Prompt({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "thai"], // สำคัญ: ต้องใส่ thai เพื่อรองรับภาษาไทย
  variable: "--font-prompt", // ตั้งชื่อตัวแปร CSS
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prompt.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
